### ISSUE TITLE
Matches do not update when deleting queryText

### ISSUE THREAD

**Issue by aforemny** [IntelliSearch/search-client#17]
Hi,
I have found that matches do not update when I delete the query text.

Steps to reproduce:
- Run the plain sample
- Search for something that generates matches, ie. `gluten`
- Press backspace until the query text is empty
- The matches do not update

**Comment by Spiralis** [comment]
It seems this is due to the trigger only saying to update if the query is longer than the configured length. It seems that we may need to consider how to handle the case where the query is shorter than the trigger-length required to fire an update. It behaves the same if you backspace to 2 or less characters. As none of them are registered to trigger. However, it may be that this trigger should have responded when there already *is* a result. Tricky one. Let me discuss this internally...

**Comment by Spiralis** [comment]
I am going to close this one. We are not using search-as-you-type by default now. Search-as-you-type opens up a whole lot of edge-cases. Postponing any potential issues with this for a later release, if necessary.
BTW: We have another callback (included in v1.0.0) that notifies the UI that the query is not matching the last executed query, making it easier for the UI to show that the current query does not match the one that created the results shown.
